### ISSUE TITLE
学校每次分配的内网IP改变该怎么解决

### ISSUE THREAD

**Issue by fukinname** [Guyiiyu/webdogcom#1]
校园网重启可能导致分配的内网IP改变，还要手动修改配置文件，有点麻烦捏

**Comment by 1v7w** [comment]
校园网一般和路由器的192.168开头以及本地127.0.开头的ip网段不同，所以可以考虑缩小子网掩码。
比如学校分配的ip可能为10.129.xxx.xxx/22，那么配置文件里可以指定:
```
network_segment = '10.129.0.0'
subnet_mask = '255.255.0.0'
```
